/**
 * ChronoSheets API
 * <div style='font-size: 14px!important;font-family: Open Sans,sans-serif!important;color: #3b4151!important;'><p>      ChronoSheets is a flexible timesheet solution for small to medium businesses, it is free for small teams of up to 3 and there are iOS and Android apps available.  Use the ChronoSheets API to create your own custom integrations.  Before starting, sign up for a ChronoSheets account at <a target='_BLANK' href='http://tsheets.xyz/signup'>http://tsheets.xyz/signup</a>.  </p></div><div id='cs-extra-info'></div>
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package ChronoSheetsClientLibModel;

import ChronoSheetsClientLibModel.ClientSeriesReportItem;
import ChronoSheetsClientLibModel.ClientTotalsReportItem;
import ChronoSheetsClientLibModel.JobSeriesReportItem;
import ChronoSheetsClientLibModel.JobTotalsReportItem;
import ChronoSheetsClientLibModel.ProjectSeriesReportItem;
import ChronoSheetsClientLibModel.ProjectTotalsReportItem;
import ChronoSheetsClientLibModel.TaskSeriesReportItem;
import ChronoSheetsClientLibModel.TaskTotalsReportItem;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class CombinedReportsData {
  
  @SerializedName("SeriesJobCodes")
  private List<JobSeriesReportItem> seriesJobCodes = null;
  @SerializedName("SeriesTasks")
  private List<TaskSeriesReportItem> seriesTasks = null;
  @SerializedName("SeriesClients")
  private List<ClientSeriesReportItem> seriesClients = null;
  @SerializedName("SeriesProjects")
  private List<ProjectSeriesReportItem> seriesProjects = null;
  @SerializedName("TotalsJobCodes")
  private List<JobTotalsReportItem> totalsJobCodes = null;
  @SerializedName("TotalsTasks")
  private List<TaskTotalsReportItem> totalsTasks = null;
  @SerializedName("TotalsClients")
  private List<ClientTotalsReportItem> totalsClients = null;
  @SerializedName("TotalsProjects")
  private List<ProjectTotalsReportItem> totalsProjects = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public List<JobSeriesReportItem> getSeriesJobCodes() {
    return seriesJobCodes;
  }
  public void setSeriesJobCodes(List<JobSeriesReportItem> seriesJobCodes) {
    this.seriesJobCodes = seriesJobCodes;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<TaskSeriesReportItem> getSeriesTasks() {
    return seriesTasks;
  }
  public void setSeriesTasks(List<TaskSeriesReportItem> seriesTasks) {
    this.seriesTasks = seriesTasks;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<ClientSeriesReportItem> getSeriesClients() {
    return seriesClients;
  }
  public void setSeriesClients(List<ClientSeriesReportItem> seriesClients) {
    this.seriesClients = seriesClients;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<ProjectSeriesReportItem> getSeriesProjects() {
    return seriesProjects;
  }
  public void setSeriesProjects(List<ProjectSeriesReportItem> seriesProjects) {
    this.seriesProjects = seriesProjects;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<JobTotalsReportItem> getTotalsJobCodes() {
    return totalsJobCodes;
  }
  public void setTotalsJobCodes(List<JobTotalsReportItem> totalsJobCodes) {
    this.totalsJobCodes = totalsJobCodes;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<TaskTotalsReportItem> getTotalsTasks() {
    return totalsTasks;
  }
  public void setTotalsTasks(List<TaskTotalsReportItem> totalsTasks) {
    this.totalsTasks = totalsTasks;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<ClientTotalsReportItem> getTotalsClients() {
    return totalsClients;
  }
  public void setTotalsClients(List<ClientTotalsReportItem> totalsClients) {
    this.totalsClients = totalsClients;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<ProjectTotalsReportItem> getTotalsProjects() {
    return totalsProjects;
  }
  public void setTotalsProjects(List<ProjectTotalsReportItem> totalsProjects) {
    this.totalsProjects = totalsProjects;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CombinedReportsData combinedReportsData = (CombinedReportsData) o;
    return (this.seriesJobCodes == null ? combinedReportsData.seriesJobCodes == null : this.seriesJobCodes.equals(combinedReportsData.seriesJobCodes)) &&
        (this.seriesTasks == null ? combinedReportsData.seriesTasks == null : this.seriesTasks.equals(combinedReportsData.seriesTasks)) &&
        (this.seriesClients == null ? combinedReportsData.seriesClients == null : this.seriesClients.equals(combinedReportsData.seriesClients)) &&
        (this.seriesProjects == null ? combinedReportsData.seriesProjects == null : this.seriesProjects.equals(combinedReportsData.seriesProjects)) &&
        (this.totalsJobCodes == null ? combinedReportsData.totalsJobCodes == null : this.totalsJobCodes.equals(combinedReportsData.totalsJobCodes)) &&
        (this.totalsTasks == null ? combinedReportsData.totalsTasks == null : this.totalsTasks.equals(combinedReportsData.totalsTasks)) &&
        (this.totalsClients == null ? combinedReportsData.totalsClients == null : this.totalsClients.equals(combinedReportsData.totalsClients)) &&
        (this.totalsProjects == null ? combinedReportsData.totalsProjects == null : this.totalsProjects.equals(combinedReportsData.totalsProjects));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.seriesJobCodes == null ? 0: this.seriesJobCodes.hashCode());
    result = 31 * result + (this.seriesTasks == null ? 0: this.seriesTasks.hashCode());
    result = 31 * result + (this.seriesClients == null ? 0: this.seriesClients.hashCode());
    result = 31 * result + (this.seriesProjects == null ? 0: this.seriesProjects.hashCode());
    result = 31 * result + (this.totalsJobCodes == null ? 0: this.totalsJobCodes.hashCode());
    result = 31 * result + (this.totalsTasks == null ? 0: this.totalsTasks.hashCode());
    result = 31 * result + (this.totalsClients == null ? 0: this.totalsClients.hashCode());
    result = 31 * result + (this.totalsProjects == null ? 0: this.totalsProjects.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class CombinedReportsData {\n");
    
    sb.append("  seriesJobCodes: ").append(seriesJobCodes).append("\n");
    sb.append("  seriesTasks: ").append(seriesTasks).append("\n");
    sb.append("  seriesClients: ").append(seriesClients).append("\n");
    sb.append("  seriesProjects: ").append(seriesProjects).append("\n");
    sb.append("  totalsJobCodes: ").append(totalsJobCodes).append("\n");
    sb.append("  totalsTasks: ").append(totalsTasks).append("\n");
    sb.append("  totalsClients: ").append(totalsClients).append("\n");
    sb.append("  totalsProjects: ").append(totalsProjects).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
