/**
 * ChronoSheets API
 * ChronoSheets is a flexible timesheet solution for small to medium businesses, it is free for small teams of up to 5 and there are iOS and Android apps available.  Use the ChronoSheets API to create your own custom integrations.
 *
 * OpenAPI spec version: v1
 * Contact: lachlan@chronosheets.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ChronoSheetsClientLibModel;

import ChronoSheetsClientLibModel.CsApiOrganisation;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class CsApiUserForManagement {
  
  @SerializedName("IsSubscribedToNewsletter")
  private Boolean isSubscribedToNewsletter = null;
  @SerializedName("IsAccountActive")
  private Boolean isAccountActive = null;
  @SerializedName("Id")
  private Integer id = null;
  @SerializedName("OrganisationId")
  private Integer organisationId = null;
  @SerializedName("UserName")
  private String userName = null;
  @SerializedName("FirstName")
  private String firstName = null;
  @SerializedName("LastName")
  private String lastName = null;
  @SerializedName("EmailAddress")
  private String emailAddress = null;
  @SerializedName("Roles")
  private Long roles = null;
  @SerializedName("AlertSettings")
  private Long alertSettings = null;
  @SerializedName("SetupWizardRequired")
  private Boolean setupWizardRequired = null;
  @SerializedName("Organisation")
  private CsApiOrganisation organisation = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getIsSubscribedToNewsletter() {
    return isSubscribedToNewsletter;
  }
  public void setIsSubscribedToNewsletter(Boolean isSubscribedToNewsletter) {
    this.isSubscribedToNewsletter = isSubscribedToNewsletter;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getIsAccountActive() {
    return isAccountActive;
  }
  public void setIsAccountActive(Boolean isAccountActive) {
    this.isAccountActive = isAccountActive;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getOrganisationId() {
    return organisationId;
  }
  public void setOrganisationId(Integer organisationId) {
    this.organisationId = organisationId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getUserName() {
    return userName;
  }
  public void setUserName(String userName) {
    this.userName = userName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getFirstName() {
    return firstName;
  }
  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getLastName() {
    return lastName;
  }
  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getEmailAddress() {
    return emailAddress;
  }
  public void setEmailAddress(String emailAddress) {
    this.emailAddress = emailAddress;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Long getRoles() {
    return roles;
  }
  public void setRoles(Long roles) {
    this.roles = roles;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Long getAlertSettings() {
    return alertSettings;
  }
  public void setAlertSettings(Long alertSettings) {
    this.alertSettings = alertSettings;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getSetupWizardRequired() {
    return setupWizardRequired;
  }
  public void setSetupWizardRequired(Boolean setupWizardRequired) {
    this.setupWizardRequired = setupWizardRequired;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public CsApiOrganisation getOrganisation() {
    return organisation;
  }
  public void setOrganisation(CsApiOrganisation organisation) {
    this.organisation = organisation;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CsApiUserForManagement userForManagement = (CsApiUserForManagement) o;
    return (this.isSubscribedToNewsletter == null ? userForManagement.isSubscribedToNewsletter == null : this.isSubscribedToNewsletter.equals(userForManagement.isSubscribedToNewsletter)) &&
        (this.isAccountActive == null ? userForManagement.isAccountActive == null : this.isAccountActive.equals(userForManagement.isAccountActive)) &&
        (this.id == null ? userForManagement.id == null : this.id.equals(userForManagement.id)) &&
        (this.organisationId == null ? userForManagement.organisationId == null : this.organisationId.equals(userForManagement.organisationId)) &&
        (this.userName == null ? userForManagement.userName == null : this.userName.equals(userForManagement.userName)) &&
        (this.firstName == null ? userForManagement.firstName == null : this.firstName.equals(userForManagement.firstName)) &&
        (this.lastName == null ? userForManagement.lastName == null : this.lastName.equals(userForManagement.lastName)) &&
        (this.emailAddress == null ? userForManagement.emailAddress == null : this.emailAddress.equals(userForManagement.emailAddress)) &&
        (this.roles == null ? userForManagement.roles == null : this.roles.equals(userForManagement.roles)) &&
        (this.alertSettings == null ? userForManagement.alertSettings == null : this.alertSettings.equals(userForManagement.alertSettings)) &&
        (this.setupWizardRequired == null ? userForManagement.setupWizardRequired == null : this.setupWizardRequired.equals(userForManagement.setupWizardRequired)) &&
        (this.organisation == null ? userForManagement.organisation == null : this.organisation.equals(userForManagement.organisation));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.isSubscribedToNewsletter == null ? 0: this.isSubscribedToNewsletter.hashCode());
    result = 31 * result + (this.isAccountActive == null ? 0: this.isAccountActive.hashCode());
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.organisationId == null ? 0: this.organisationId.hashCode());
    result = 31 * result + (this.userName == null ? 0: this.userName.hashCode());
    result = 31 * result + (this.firstName == null ? 0: this.firstName.hashCode());
    result = 31 * result + (this.lastName == null ? 0: this.lastName.hashCode());
    result = 31 * result + (this.emailAddress == null ? 0: this.emailAddress.hashCode());
    result = 31 * result + (this.roles == null ? 0: this.roles.hashCode());
    result = 31 * result + (this.alertSettings == null ? 0: this.alertSettings.hashCode());
    result = 31 * result + (this.setupWizardRequired == null ? 0: this.setupWizardRequired.hashCode());
    result = 31 * result + (this.organisation == null ? 0: this.organisation.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class CsApiUserForManagement {\n");
    
    sb.append("  isSubscribedToNewsletter: ").append(isSubscribedToNewsletter).append("\n");
    sb.append("  isAccountActive: ").append(isAccountActive).append("\n");
    sb.append("  id: ").append(id).append("\n");
    sb.append("  organisationId: ").append(organisationId).append("\n");
    sb.append("  userName: ").append(userName).append("\n");
    sb.append("  firstName: ").append(firstName).append("\n");
    sb.append("  lastName: ").append(lastName).append("\n");
    sb.append("  emailAddress: ").append(emailAddress).append("\n");
    sb.append("  roles: ").append(roles).append("\n");
    sb.append("  alertSettings: ").append(alertSettings).append("\n");
    sb.append("  setupWizardRequired: ").append(setupWizardRequired).append("\n");
    sb.append("  organisation: ").append(organisation).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
