/**
 * The ChronoSheets API
 * <div style='font-size: 14px!important;font-family: Open Sans,sans-serif!important;color: #3b4151!important;'><p>      ChronoSheets is a flexible timesheet solution for small to medium businesses, it is free for small teams of up to 5 and there are iOS and Android apps available.  Use the ChronoSheets API to create your own custom integrations.  Before starting, sign up for a ChronoSheets account at <a target='_BLANK' href='http://tsheets.xyz/signup'>http://tsheets.xyz/signup</a>.  </p></div><div id='cs-extra-info'></div>
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ChronoSheetsClientLibModel;

import ChronoSheetsClientLibModel.CSClientSideUser;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * A Response object containing important information that can be used after the user has logged in
 **/
@ApiModel(description = "A Response object containing important information that can be used after the user has logged in")
public class CSDoLoginResponse {
  
  @SerializedName("CSAuthToken")
  private String cSAuthToken = null;
  @SerializedName("LoggedInUser")
  private CSClientSideUser loggedInUser = null;

  /**
   * The ChronoSheets Auth Token.  Use this token for all subsequent requests to the API.  The Auth Token does these things: holds your session and gives you appropraite authorisation to access API endpoints based on your UserRoles
   **/
  @ApiModelProperty(value = "The ChronoSheets Auth Token.  Use this token for all subsequent requests to the API.  The Auth Token does these things: holds your session and gives you appropraite authorisation to access API endpoints based on your UserRoles")
  public String getCSAuthToken() {
    return cSAuthToken;
  }
  public void setCSAuthToken(String cSAuthToken) {
    this.cSAuthToken = cSAuthToken;
  }

  /**
   * An object containg all your account information
   **/
  @ApiModelProperty(value = "An object containg all your account information")
  public CSClientSideUser getLoggedInUser() {
    return loggedInUser;
  }
  public void setLoggedInUser(CSClientSideUser loggedInUser) {
    this.loggedInUser = loggedInUser;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CSDoLoginResponse doLoginResponse = (CSDoLoginResponse) o;
    return (this.cSAuthToken == null ? doLoginResponse.cSAuthToken == null : this.cSAuthToken.equals(doLoginResponse.cSAuthToken)) &&
        (this.loggedInUser == null ? doLoginResponse.loggedInUser == null : this.loggedInUser.equals(doLoginResponse.loggedInUser));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.cSAuthToken == null ? 0: this.cSAuthToken.hashCode());
    result = 31 * result + (this.loggedInUser == null ? 0: this.loggedInUser.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class CSDoLoginResponse {\n");
    
    sb.append("  cSAuthToken: ").append(cSAuthToken).append("\n");
    sb.append("  loggedInUser: ").append(loggedInUser).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
