/**
 * ChronoSheets API
 * ChronoSheets is a flexible timesheet solution for small to medium businesses, it is free for small teams of up to 5 and there are iOS and Android apps available.  Use the ChronoSheets API to create your own custom integrations.
 *
 * OpenAPI spec version: v1
 * Contact: lachlan@chronosheets.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ChronoSheetsClientLibModel;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class CSInsertUserJobFavouriteRequest {
  
  @SerializedName("JobId")
  private Integer jobId = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getJobId() {
    return jobId;
  }
  public void setJobId(Integer jobId) {
    this.jobId = jobId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CSInsertUserJobFavouriteRequest insertUserJobFavouriteRequest = (CSInsertUserJobFavouriteRequest) o;
    return (this.jobId == null ? insertUserJobFavouriteRequest.jobId == null : this.jobId.equals(insertUserJobFavouriteRequest.jobId));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.jobId == null ? 0: this.jobId.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class CSInsertUserJobFavouriteRequest {\n");
    
    sb.append("  jobId: ").append(jobId).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
